Solution
danikirillov/wheel pull request #1
Opened 2024-01-16 20:19 UTC by Sergei-Nerobeev

2024-01-16 23:14 UTC, danikirillov requested changes
Хорошее начало, я оставил комментарии, жду фиксы

2024-01-16 23:14 UTC, danikirillov commented on src/ru/danikirillov/Car.java
> +      if (wheels[i].isFlat() == true) {
сравнивать с тру и фолс - нехорошо. 

Вот, что у тебя написано:
Если (колесо.проколото == тру) ...

== тру выглядит инородно. Ведь и без него все понятно:
Если (колесо.проколото) ...

2024-01-16 23:14 UTC, danikirillov commented on src/ru/danikirillov/Car.java
> +    for (int i = 0; i < wheels.length; i++) {
способ оригинальный, но первый элемент массива можно получить проще - wheels[0]

2024-01-16 23:14 UTC, danikirillov commented on src/ru/danikirillov/Car.java
> +          wheels[i].getRadius() == wheelForReplacement.getRadius()) {
Функция этого метода - замена колеса. Проверка колеса, которое тебе дали для замены, происходит в публичном методе replaceFlatWheel выше. Поэтому тут она лишняя.

2024-01-16 23:14 UTC, danikirillov commented on src/ru/danikirillov/Car.java
> +          wheels[i].setFlat(false);
В теории, так как наше колесо обладает всего двумя атрибутами можно было бы принять такой подход замены.
Но мы следуем тз. В нем написано чендж вил, а не фикс вил. Поэтому тут тоже надо исправить. 

Также в метод приходит всего одно колесо на замену, а твое решение получается "чинит" все прохудившиеся колеса. Не реалистично:)

2024-01-19 23:22 UTC, danikirillov commented on src/ru/danikirillov/Car.java
> +    {
это как? (конструкция иф {...}{...}  a елсе где?:)

2024-01-19 23:27 UTC, danikirillov commented on src/ru/danikirillov/Car.java
> +    return false;
хорошо

2024-01-19 23:36 UTC, danikirillov commented on src/ru/danikirillov/App.java
> +      System.out.println("changeGoodWheelsNoErrorTest - ERROR!!!!!!!!!!! - wheel hasn't been changed");
as i said in the line 12 - logically each unit test contains 3 parts. So put blank lines between them - that will make it much easier for other developers to understand your code.

```suggestion
    final var wheel = new Wheel(false, radius);
    
    car.replaceFlatWheel(wheel);
    
    if (car.isAnyWheelFlat()) {
      System.out.println("changeGoodWheelsNoErrorTest - ERROR!!!!!!!!!!! - wheel hasn't been changed");
```

2024-01-19 23:37 UTC, danikirillov commented on src/ru/danikirillov/App.java
> +      System.out.println("changeGoodWheelsNoErrorTest - ERROR!!!!!!!!!!! - wheel hasn't been changed");
the same for other tests

2024-01-19 23:42 UTC, danikirillov commented on src/ru/danikirillov/App.java
> +  }
Такая просьба - напиши тут в гитхабе ответом на это сообщение все, что делает этот метод - по строкам.
Я начну:
45 - описывается метод, возвращающий целое число, судя по названию - проверяет, что будет если попробовать поменять колесо на колесо с неправильным радиусом
46 - создается переменная радиус, равная 17

2024-01-20 23:19 UTC, Sergei-Nerobeev commented on src/ru/danikirillov/App.java
> +  }
> Такая просьба - напиши тут в гитхабе ответом на это сообщение все, что делает этот метод - по строкам. Я начну: 45 - описывается метод, возвращающий целое число, судя по названию - проверяет, что будет если попробовать поменять колесо на колесо с неправильным радиусом 46 - создается переменная радиус, равная 17
47 - создается переменная типа Автомобиль, со свойствами ХорошийАвтомобиль с радиусом.. и тут я понял, что я написал))) что-то очень странное и непонятно, что проверяющее)))

2024-03-08 21:39 UTC, merged